#pragma warning disable CS1591 // Missing XML comment for publicly visible type or member

namespace ktsu.io.SchemaLib;

using ktsu.io.StrongPaths;

public abstract class SchemaCodeGenerator
{
	protected const string FileComment = "Auto-generated by SchemaCodeGenerator - Do not manually edit!";

	public bool Enabled { get; set; } = true;
	public RelativeDirectoryPath OutputDirectory { get; set; } = new();

	protected abstract void GenerateCodeFor(Schema schema);
	protected abstract void GenerateCodeFor(SchemaClass schemaClass);
	protected abstract void GenerateCodeFor(SchemaEnum schemaEnum);
	protected abstract void GenerateCodeFor(SchemaMember schemaMember);
}
